```
{
  "CVE-2019-5010": {
    "description": "An exploitable denial-of-service vulnerability exists in the X509 certificate parser of Python.org Python 2.7.11 / 3.6.6. A specially crafted X509 certificate can cause a NULL pointer dereference, resulting in a denial of service. An attacker can initiate or accept TLS connections using crafted certificates to trigger this vulnerability.",
    "vulnerability_details": {
      "root_cause": "The vulnerability is caused by a NULL pointer dereference when processing a specially crafted X509 certificate. The vulnerability exists when a DistributionPoint with both a blank `distributionPoint` and a blank `cRLIssuer` is present in the certificate's extension, leading to a crash when `_get_crl_dp()` function attempts to access the distpoint->name.fullname.",
      "weaknesses": [
        "NULL pointer dereference",
        "Improper validation of X509 certificate's DistributionPoint extension"
      ],
      "impact": "A remote attacker can cause a denial of service condition by sending a specially crafted X509 certificate to a server or client during a TLS handshake, or when the getpeercert() function is called with a crafted certificate, causing the application using the vulnerable Python library to crash",
      "attack_vectors": [
        "Network",
         "Specially crafted X509 certificate."
      ],
      "attacker_capabilities": "The attacker must be able to send a malicious X509 certificate during the TLS handshake or to an application that processes certificates. The certificate has to be trusted by the remote party (victim), as handshake failures (e.g., untrusted CA) results in skipping the call to `getpeercert()`."
    }
  }
}
```